import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={
            "mx-auto max-w-[1000px] px-6 pb-24 pt-16 md:px-6 md:pb-44 md:pt-20 bg-primary text-primary"
          }
        >
          {children}
        </div>
      </body>
    </html>
  )
}
